### ISSUE TITLE
Deep Link Dead ;)

### ISSUE THREAD

**Issue by karstengresch** [quarkus-for-spring-developers/examples#221]
Hi @edeandrea ,

as this is for me the quickest way to inform about this issue:

[README.md](https://github.com/quarkus-for-spring-developers/examples/blob/main/README.md) uses a shortcut link (https://red.ht/quarkus-spring-devs) resolving to https://developers.redhat.com/e-books/quarkus-spring-developers where your eBook (i.e. PDF) is offered as download.

Alas, the download link is https://developers.redhat.com/content-gateway/file/Quarkus-For-Spring-Developers-Red-Hat.pdf and doesn't seem to be served: the comments on the site indicate this as well as the error message 

```
Oops - Something's wrong!

Bad Request

Your browser sent a request that the server didn't like.

Please modify it and try again.
```
![image](https://user-images.githubusercontent.com/7924413/199722786-8e2d2f2b-5623-48f3-b652-0a2bd4b17f37.png)

The bad redirect goes to urls like https://developers.redhat.com/content-gateway/rest/keycloak?state=386299a3-d045-447d-a9ce-287bb82e8742&session_state=7ec9c09f-fb91-4231-9d90-3b373d8d42e6&code=dae29fd9-387e-4b54-ac46-c156735b86ef.7ec9c09f-fb91-4231-9d90-3b373d8d42e6.4d385286-7e7c-4fba-9d01-3b8921e5ca70 

Perhaps it's possible to attach the ebook here or to fix the link?

**Comment by edeandrea** [comment]
Hi @karstengresch thank you for reporting this. I will take this up with the developers.redhat.com team. Unfortunately I can not simply place the pdf here due to contractual obligations with Red Hat.

**Comment by edeandrea** [comment]
It seems to be a broader issue that affects more than just this e-book. The team is working on getting it resolved. I will update you here once it has been resolved.

**Comment by karstengresch** [comment]
Hi @edeandrea - thanks very much (also for not being angry getting informed via this channel), it's an honor!

**Comment by edeandrea** [comment]
Hi @karstengresch I just wanted to circle back and let you know that the download issue should have been resolved last week.

I just tried it myself and it seems to be fine. Please let me know if this is still an issue? If not, I will go ahead and close this issue.
